//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace GustoEmbedded.Models.Errors
{
    using GustoEmbedded.Models.Components;
    using GustoEmbedded.Models.Errors;
    using GustoEmbedded.Utils;
    using Newtonsoft.Json;
    using System;
    
    /// <summary>
    /// Unprocessable Entity (WebDAV)
    /// </summary>
    public class GetCompaniesCompanyUuidContractorPaymentsPreviewResponseBody : Exception
    {

        [JsonProperty("errors")]
        public GetCompaniesCompanyUuidContractorPaymentsPreviewErrors? Errors { get; set; }

        [JsonProperty("-")]
        public HTTPMetadata HttpMeta { get; set; } = default!;
    }
}