workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Gusto-OAS:
        inputs:
            - location: https://raw.githubusercontent.com/Gusto/Gusto-Partner-API/refs/heads/main/generated/embedded/api.v2025-06-15.embedded.yaml
              authHeader: Authorization
              authSecret: $openapi_doc_auth_token
        overlays:
            - location: https://raw.githubusercontent.com/Gusto/Gusto-Partner-API/refs/heads/main/.speakeasy/speakeasy-modifications-overlay.yaml
              authHeader: Authorization
              authSecret: $openapi_doc_auth_token
            - location: gusto_embedded/.speakeasy/speakeasy-modifications-overlay.yaml
        registry:
            location: registry.speakeasyapi.dev/gusto/ruby-sdk/gusto-oas
targets:
    gusto:
        target: csharp
        source: Gusto-OAS
        output: ./gusto_embedded
        publish:
            nuget:
                apiKey: $nuget_api_key
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/gusto/ruby-sdk/gusto-oas-csharp-code-samples
            labelOverride:
                fixedValue: Csharp (SDK)
            blocking: false
