//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace GustoEmbedded.Models.Components
{
    using GustoEmbedded.Utils;
    using Newtonsoft.Json;
    
    public class ApplicableEarnings
    {

        [JsonProperty("earning_type")]
        public string? EarningType { get; set; }

        [JsonProperty("earning_id")]
        public double? EarningId { get; set; }

        [JsonProperty("name")]
        public string? Name { get; set; }

        [JsonProperty("input_type")]
        public string? InputType { get; set; }

        [JsonProperty("category")]
        public string? Category { get; set; }
    }
}