//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace GustoEmbedded.Models.Components
{
    using GustoEmbedded.Models.Components;
    using GustoEmbedded.Utils;
    using Newtonsoft.Json;
    
    /// <summary>
    /// Record representing the suspension of a company&apos;s Gusto account.
    /// </summary>
    public class CompanySuspension
    {

        /// <summary>
        /// Unique identifier for this suspension.
        /// </summary>
        [JsonProperty("uuid")]
        public string? Uuid { get; set; }

        /// <summary>
        /// Unique identifier for the company which is suspended.
        /// </summary>
        [JsonProperty("company_uuid")]
        public string? CompanyUuid { get; set; }

        /// <summary>
        /// Date that the suspension took effect.
        /// </summary>
        [JsonProperty("effective_date")]
        public string? EffectiveDate { get; set; }

        /// <summary>
        /// Which competitor the company is joining instead. Only required if `reason` is `&apos;switching_provider&apos;`.
        /// </summary>
        [JsonProperty("leaving_for")]
        public string? LeavingFor { get; set; }

        /// <summary>
        /// Explanation for why the company&apos;s account was suspended.
        /// </summary>
        [JsonProperty("reason")]
        public string? Reason { get; set; }

        /// <summary>
        /// How Gusto will handle taxes already collected.
        /// </summary>
        [JsonProperty("reconcile_tax_method")]
        public Models.Components.ReconcileTaxMethod? ReconcileTaxMethod { get; set; }

        /// <summary>
        /// Should Gusto file quarterly tax forms on behalf of the company? The correct answer can depend on why the company<br/>
        /// 
        /// <remarks>
        /// is suspending their account, and how taxes are being reconciled.<br/>
        /// 
        /// </remarks>
        /// </summary>
        [JsonProperty("file_quarterly_forms")]
        public bool? FileQuarterlyForms { get; set; }

        /// <summary>
        /// Should Gusto file yearly tax forms on behalf of the company? The correct answer can depend on why the company<br/>
        /// 
        /// <remarks>
        /// is suspending their account, and how taxes are being reconciled.<br/>
        /// 
        /// </remarks>
        /// </summary>
        [JsonProperty("file_yearly_forms")]
        public bool? FileYearlyForms { get; set; }

        /// <summary>
        /// User-supplied comments describing why then are suspending their account.
        /// </summary>
        [JsonProperty("comments")]
        public string? Comments { get; set; }

        /// <summary>
        /// Describes the taxes which are refundable to the company for this suspension. These may be refunded, or paid<br/>
        /// 
        /// <remarks>
        /// by Gusto, depending on the value in `reconcile_tax_method`.<br/>
        /// 
        /// </remarks>
        /// </summary>
        [JsonProperty("tax_refunds")]
        public TaxRefunds? TaxRefunds { get; set; }
    }
}