//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace GustoEmbedded.Models.Components
{
    using GustoEmbedded.Models.Components;
    using GustoEmbedded.Utils;
    using Newtonsoft.Json;
    using System.Collections.Generic;
    
    /// <summary>
    /// The representation of the summary of contractor payments for a given company in a given time period.
    /// </summary>
    public class ContractorPaymentSummaryByDates
    {

        /// <summary>
        /// The wage and reimbursement totals for all contractor payments within a given time period.
        /// </summary>
        [JsonProperty("total")]
        public ContractorPaymentSummaryByDatesTotal? Total { get; set; }

        /// <summary>
        /// The individual contractor payments, within a given time period, grouped by check date.
        /// </summary>
        [JsonProperty("contractor_payments")]
        public List<ContractorPaymentSummaryByDatesContractorPayments>? ContractorPayments { get; set; }
    }
}