//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace GustoEmbedded.Models.Components
{
    using GustoEmbedded.Models.Components;
    using GustoEmbedded.Utils;
    using Newtonsoft.Json;
    using System.Collections.Generic;
    
    /// <summary>
    /// The amount that the employee is insured for. Note: company contribution cannot be present if coverage amount is set.
    /// </summary>
    public class CoverageAmount
    {

        [JsonProperty("required")]
        public bool? Required { get; set; }

        [JsonProperty("editable")]
        public bool? Editable { get; set; }

        [JsonProperty("default_value")]
        public BenefitTypeRequirementsCoverageAmountDefaultValue? DefaultValue { get; set; }

        [JsonProperty("choices")]
        public List<string>? Choices { get; set; }
    }
}