//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace GustoEmbedded.Models.Components
{
    using GustoEmbedded.Models.Components;
    using GustoEmbedded.Utils;
    using Newtonsoft.Json;
    
    /// <summary>
    /// Representation of an Event
    /// </summary>
    public class Event
    {

        /// <summary>
        /// Unique identifier for the event.
        /// </summary>
        [JsonProperty("uuid")]
        public string Uuid { get; set; } = default!;

        /// <summary>
        /// Description of the event (e.g., payroll.submitted, or company.form.signed).
        /// </summary>
        [JsonProperty("event_type")]
        public string? EventType { get; set; }

        /// <summary>
        /// Name of the parent resource of the described entity.
        /// </summary>
        [JsonProperty("resource_type")]
        public ResourceType? ResourceType { get; set; }

        /// <summary>
        /// Unique identifier for the parent resource.
        /// </summary>
        [JsonProperty("resource_uuid")]
        public string? ResourceUuid { get; set; }

        /// <summary>
        /// Name of the entity that the event corresponds to.
        /// </summary>
        [JsonProperty("entity_type")]
        public string? EntityType { get; set; }

        /// <summary>
        /// Unique identifier for the entity.
        /// </summary>
        [JsonProperty("entity_uuid")]
        public string? EntityUuid { get; set; }

        /// <summary>
        /// Time at which this event was created. Measured in seconds since the Unix epoch.
        /// </summary>
        [JsonProperty("timestamp")]
        public long? Timestamp { get; set; }
    }
}