//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace GustoEmbedded.Models.Components
{
    using GustoEmbedded.Models.Components;
    using GustoEmbedded.Utils;
    using Newtonsoft.Json;
    
    /// <summary>
    /// Garnishments, or employee deductions, are fixed amounts or percentages deducted from an employee’s pay. They can be deducted a specific number of times or on a recurring basis. Garnishments can also have maximum deductions on a yearly or per-pay-period bases. Common uses for garnishments are court-ordered payments for child support or back taxes. Some companies provide loans to their employees that are repaid via garnishments.
    /// </summary>
    public class Garnishment
    {

        /// <summary>
        /// The UUID of the garnishment in Gusto.
        /// </summary>
        [JsonProperty("uuid")]
        public string Uuid { get; set; } = default!;

        /// <summary>
        /// The current version of the object. See the <a href="https://docs.gusto.com/embedded-payroll/docs/idempotency">versioning guide</a> for information on how to use this field.
        /// </summary>
        [JsonProperty("version")]
        public string? Version { get; set; }

        /// <summary>
        /// The UUID of the employee to which this garnishment belongs.
        /// </summary>
        [JsonProperty("employee_uuid")]
        public string? EmployeeUuid { get; set; }

        /// <summary>
        /// Whether or not this garnishment is currently active.
        /// </summary>
        [JsonProperty("active")]
        public bool? Active { get; set; } = true;

        /// <summary>
        /// The amount of the garnishment. Either a percentage or a fixed dollar amount. Represented as a float, e.g. &quot;8.00&quot;.
        /// </summary>
        [JsonProperty("amount")]
        public string? Amount { get; set; }

        /// <summary>
        /// The description of the garnishment.
        /// </summary>
        [JsonProperty("description")]
        public string? Description { get; set; }

        /// <summary>
        /// Whether the garnishment is court ordered.
        /// </summary>
        [JsonProperty("court_ordered")]
        public bool? CourtOrdered { get; set; }

        /// <summary>
        /// The number of times to apply the garnishment. Ignored if recurring is true.
        /// </summary>
        [JsonProperty("times")]
        public long? Times { get; set; } = null;

        /// <summary>
        /// Whether the garnishment should recur indefinitely.
        /// </summary>
        [JsonProperty("recurring")]
        public bool? Recurring { get; set; } = false;

        /// <summary>
        /// The maximum deduction per annum. A null value indicates no maximum. Represented as a float, e.g. &quot;200.00&quot;.
        /// </summary>
        [JsonProperty("annual_maximum")]
        public string? AnnualMaximum { get; set; } = null;

        /// <summary>
        /// A maximum total deduction for the lifetime of this garnishment. A null value indicates no maximum.
        /// </summary>
        [JsonProperty("total_amount")]
        public string? TotalAmount { get; set; } = null;

        /// <summary>
        /// The maximum deduction per pay period. A null value indicates no maximum. Represented as a float, e.g. &quot;16.00&quot;.
        /// </summary>
        [JsonProperty("pay_period_maximum")]
        public string? PayPeriodMaximum { get; set; } = null;

        /// <summary>
        /// Whether the amount should be treated as a percentage to be deducted per pay period.
        /// </summary>
        [JsonProperty("deduct_as_percentage")]
        public bool? DeductAsPercentage { get; set; } = false;

        /// <summary>
        /// The specific type of garnishment for court ordered garnishments.
        /// </summary>
        [JsonProperty("garnishment_type")]
        public Models.Components.GarnishmentType? GarnishmentType { get; set; } = null;

        /// <summary>
        /// Additional child support order details
        /// </summary>
        [JsonProperty("child_support")]
        public GarnishmentChildSupport? ChildSupport { get; set; } = null;
    }
}