//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace GustoEmbedded.Models.Components
{
    using GustoEmbedded.Utils;
    using Newtonsoft.Json;
    
    /// <summary>
    /// An employee&apos;s I-9 verification document
    /// </summary>
    public class I9AuthorizationDocument
    {

        /// <summary>
        /// The UUID of the I-9 verification document
        /// </summary>
        [JsonProperty("uuid")]
        public string Uuid { get; set; } = default!;

        /// <summary>
        /// The document&apos;s document type
        /// </summary>
        [JsonProperty("document_type")]
        public string DocumentType { get; set; } = default!;

        /// <summary>
        /// The document&apos;s document title
        /// </summary>
        [JsonProperty("document_title")]
        public string DocumentTitle { get; set; } = default!;

        /// <summary>
        /// The document&apos;s expiration date
        /// </summary>
        [JsonProperty("expiration_date")]
        public string? ExpirationDate { get; set; }

        /// <summary>
        /// The document&apos;s issuing authority
        /// </summary>
        [JsonProperty("issuing_authority")]
        public string IssuingAuthority { get; set; } = default!;
    }
}