//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace GustoEmbedded.Models.Components
{
    using GustoEmbedded.Utils;
    using Newtonsoft.Json;
    using System;
    
    /// <summary>
    /// The document&apos;s document type
    /// </summary>
    public enum I9AuthorizationDocumentType
    {
        [JsonProperty("uscis_alien_registration_number")]
        UscisAlienRegistrationNumber,
        [JsonProperty("form_i94")]
        FormI94,
        [JsonProperty("foreign_passport")]
        ForeignPassport,
    }

    public static class I9AuthorizationDocumentTypeExtension
    {
        public static string Value(this I9AuthorizationDocumentType value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static I9AuthorizationDocumentType ToEnum(this string value)
        {
            foreach(var field in typeof(I9AuthorizationDocumentType).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is I9AuthorizationDocumentType)
                    {
                        return (I9AuthorizationDocumentType)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum I9AuthorizationDocumentType");
        }
    }

}