//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace GustoEmbedded.Models.Components
{
    using GustoEmbedded.Utils;
    using Newtonsoft.Json;
    using System.Collections.Generic;
    
    /// <summary>
    /// single entity
    /// </summary>
    public class MetadataWithOneEntity
    {

        /// <summary>
        /// Name of the entity that the error corresponds to.
        /// </summary>
        [JsonProperty("entity_type")]
        public string? EntityType { get; set; }

        /// <summary>
        /// Unique identifier for the entity.
        /// </summary>
        [JsonProperty("entity_uuid")]
        public string? EntityUuid { get; set; }

        [JsonProperty("valid_from")]
        public string? ValidFrom { get; set; } = null;

        [JsonProperty("valid_up_to")]
        public string? ValidUpTo { get; set; } = null;

        [JsonProperty("key")]
        public string? Key { get; set; } = null;

        [JsonProperty("state")]
        public string? State { get; set; } = null;

        [JsonProperty("additionalProperties")]
        public Dictionary<string, object>? AdditionalProperties { get; set; }
    }
}