//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace GustoEmbedded.Models.Components
{
    using GustoEmbedded.Utils;
    using Newtonsoft.Json;
    using System;
    
    /// <summary>
    /// The off-cycle reason. Only included for off-cycle payrolls.
    /// </summary>
    public enum OffCycleReasonType
    {
        [JsonProperty("Benefit reversal")]
        BenefitReversal,
        [JsonProperty("Bonus")]
        Bonus,
        [JsonProperty("Correction")]
        Correction,
        [JsonProperty("Dismissed employee")]
        DismissedEmployee,
        [JsonProperty("Hired employee")]
        HiredEmployee,
        [JsonProperty("Wage correction")]
        WageCorrection,
        [JsonProperty("Tax reconciliation")]
        TaxReconciliation,
        [JsonProperty("Reversal")]
        Reversal,
        [JsonProperty("Disability insurance distribution")]
        DisabilityInsuranceDistribution,
        [JsonProperty("Transition from old pay schedule")]
        TransitionFromOldPaySchedule,
    }

    public static class OffCycleReasonTypeExtension
    {
        public static string Value(this OffCycleReasonType value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static OffCycleReasonType ToEnum(this string value)
        {
            foreach(var field in typeof(OffCycleReasonType).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is OffCycleReasonType)
                    {
                        return (OffCycleReasonType)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum OffCycleReasonType");
        }
    }

}