//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace GustoEmbedded.Models.Components
{
    using GustoEmbedded.Utils;
    using Newtonsoft.Json;
    
    /// <summary>
    /// Configuration for an employee onboarding documents during onboarding
    /// </summary>
    public class OnboardingDocumentsConfig
    {

        /// <summary>
        /// The UUID of the onboarding documents config
        /// </summary>
        [JsonProperty("uuid")]
        public string? Uuid { get; set; } = null;

        /// <summary>
        /// Whether to include Form I-9 for an employee during onboarding
        /// </summary>
        [JsonProperty("i9_document")]
        public bool? I9Document { get; set; }
    }
}