//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace GustoEmbedded.Models.Components
{
    using GustoEmbedded.Utils;
    using Newtonsoft.Json;
    
    public class PayScheduleAssignmentEmployee
    {

        /// <summary>
        /// The UUID of the employee.
        /// </summary>
        [JsonProperty("employee_uuid")]
        public string? EmployeeUuid { get; set; }

        /// <summary>
        /// The employee&apos;s pay schedule UUID.
        /// </summary>
        [JsonProperty("pay_schedule_uuid")]
        public string? PayScheduleUuid { get; set; }
    }
}