//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace GustoEmbedded.Models.Components
{
    using GustoEmbedded.Models.Components;
    using GustoEmbedded.Utils;
    using Newtonsoft.Json;
    using System.Collections.Generic;
    
    /// <summary>
    /// The representation of a pay schedule assignment preview.
    /// </summary>
    public class PayScheduleAssignmentPreview
    {

        /// <summary>
        /// The pay schedule assignment type.
        /// </summary>
        [JsonProperty("type")]
        public PayScheduleAssignmentPreviewType? Type { get; set; } = null;

        /// <summary>
        /// A list of pay schedule changes including pay period and transition pay period.
        /// </summary>
        [JsonProperty("employee_changes")]
        public List<PayScheduleAssignmentEmployeeChange>? EmployeeChanges { get; set; }
    }
}