//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace GustoEmbedded.Models.Components
{
    using GustoEmbedded.Utils;
    using Newtonsoft.Json;
    
    /// <summary>
    /// The representation of an unprocessed termination pay period.
    /// </summary>
    public class UnprocessedTerminationPayPeriod
    {

        /// <summary>
        /// The start date of the pay period.
        /// </summary>
        [JsonProperty("start_date")]
        public string? StartDate { get; set; }

        /// <summary>
        /// The end date of the pay period.
        /// </summary>
        [JsonProperty("end_date")]
        public string? EndDate { get; set; }

        /// <summary>
        /// The check date of the pay period.
        /// </summary>
        [JsonProperty("check_date")]
        public string? CheckDate { get; set; }

        /// <summary>
        /// The debit date of the pay period.
        /// </summary>
        [JsonProperty("debit_date")]
        public string? DebitDate { get; set; }

        /// <summary>
        /// The full name of the employee.
        /// </summary>
        [JsonProperty("employee_name")]
        public string? EmployeeName { get; set; }

        /// <summary>
        /// A unique identifier of the employee.
        /// </summary>
        [JsonProperty("employee_uuid")]
        public string? EmployeeUuid { get; set; }

        /// <summary>
        /// A unique identifier of the pay schedule to which the pay period belongs.
        /// </summary>
        [JsonProperty("pay_schedule_uuid")]
        public string? PayScheduleUuid { get; set; }
    }
}