//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace GustoEmbedded.Models.Components
{
    using GustoEmbedded.Utils;
    using Newtonsoft.Json;
    using System;
    
    /// <summary>
    /// The verification type of the bank account.<br/>
    /// 
    /// <remarks>
    /// <br/>
    /// &apos;bank_deposits&apos; means the bank account is connected by entering routing and accounting numbers and verifying through micro-deposits.<br/>
    /// &apos;plaid&apos; means the bank account is connected through Plaid.
    /// </remarks>
    /// </summary>
    public enum VerificationType
    {
        [JsonProperty("bank_deposits")]
        BankDeposits,
        [JsonProperty("plaid")]
        Plaid,
        [JsonProperty("plaid_external")]
        PlaidExternal,
    }

    public static class VerificationTypeExtension
    {
        public static string Value(this VerificationType value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static VerificationType ToEnum(this string value)
        {
            foreach(var field in typeof(VerificationType).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is VerificationType)
                    {
                        return (VerificationType)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum VerificationType");
        }
    }

}