//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace GustoEmbedded.Models.Components
{
    using GustoEmbedded.Utils;
    using Newtonsoft.Json;
    
    public class ActiveCompanies
    {

        /// <summary>
        /// unique identifier for the company associated with the invoice data
        /// </summary>
        [JsonProperty("company_uuid")]
        public string? CompanyUuid { get; set; }

        /// <summary>
        /// The number of active employees the company was or will be invoiced for that invoice period. Active employees are calculated as the count of onboarded employees hired before the end of the invoice period and not terminated before the start of the invoice period.
        /// </summary>
        [JsonProperty("active_employees")]
        public long? ActiveEmployees { get; set; }

        /// <summary>
        /// The number of active contractors the company was or will be invoiced for that invoice period. Active contractors are calculated as any contractor with an active contractor payment during the invoice period.
        /// </summary>
        [JsonProperty("active_contractors")]
        public long? ActiveContractors { get; set; }

        /// <summary>
        /// The first invoice period for the company. This will either be the invoice period of the first invoice-able event (first payroll or contractor payment) or the date they migrated to embedded, whichever is later.
        /// </summary>
        [JsonProperty("initial_invoice_period")]
        public string? InitialInvoicePeriod { get; set; }
    }
}