//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace GustoEmbedded.Models.Components
{
    using GustoEmbedded.Models.Components;
    using GustoEmbedded.Utils;
    using Newtonsoft.Json;
    
    public class EmployeeBenefits
    {

        /// <summary>
        /// The UUID of the employee to which the benefit belongs.
        /// </summary>
        [JsonProperty("employee_uuid")]
        public string? EmployeeUuid { get; set; }

        /// <summary>
        /// The UUID of the company benefit.
        /// </summary>
        [JsonProperty("company_benefit_uuid")]
        public string? CompanyBenefitUuid { get; set; }

        /// <summary>
        /// Whether the employee benefit is active.
        /// </summary>
        [JsonProperty("active")]
        public bool? Active { get; set; } = true;

        /// <summary>
        /// Whether the employee deduction amount should be treated as a percentage to be deducted from each payroll.
        /// </summary>
        [JsonProperty("deduct_as_percentage")]
        public bool? DeductAsPercentage { get; set; } = false;

        /// <summary>
        /// The amount to be deducted, per pay period, from the employee&apos;s pay.
        /// </summary>
        [JsonProperty("employee_deduction")]
        public string? EmployeeDeduction { get; set; } = "0.00";

        /// <summary>
        /// The value of the company contribution
        /// </summary>
        [JsonProperty("company_contribution")]
        public string? CompanyContribution { get; set; }

        [JsonProperty("uuid")]
        public string? Uuid { get; set; }

        /// <summary>
        /// An object representing the type and value of the company contribution.
        /// </summary>
        [JsonProperty("contribution")]
        public CompanyBenefitWithEmployeeBenefitsContribution? Contribution { get; set; }
    }
}