//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace GustoEmbedded.Models.Components
{
    using GustoEmbedded.Models.Components;
    using GustoEmbedded.Utils;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using System;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;
    

    public class EmployeeBenefitForCompanyBenefitValueType
    {
        private EmployeeBenefitForCompanyBenefitValueType(string value) { Value = value; }

        public string Value { get; private set; }
        public static EmployeeBenefitForCompanyBenefitValueType Str { get { return new EmployeeBenefitForCompanyBenefitValueType("str"); } }
        
        public static EmployeeBenefitForCompanyBenefitValueType Value2 { get { return new EmployeeBenefitForCompanyBenefitValueType("value_2"); } }
        
        public static EmployeeBenefitForCompanyBenefitValueType Null { get { return new EmployeeBenefitForCompanyBenefitValueType("null"); } }

        public override string ToString() { return Value; }
        public static implicit operator String(EmployeeBenefitForCompanyBenefitValueType v) { return v.Value; }
        public static EmployeeBenefitForCompanyBenefitValueType FromString(string v) {
            switch(v) {
                case "str": return Str;
                case "value_2": return Value2;
                case "null": return Null;
                default: throw new ArgumentException("Invalid value for EmployeeBenefitForCompanyBenefitValueType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((EmployeeBenefitForCompanyBenefitValueType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }


    /// <summary>
    /// For the `amount` and `percentage` contribution types, the value of the corresponding amount or percentage.<br/>
    /// 
    /// <remarks>
    /// <br/>
    /// For the `tiered` contribution type, an array of tiers.
    /// </remarks>
    /// </summary>
    [JsonConverter(typeof(EmployeeBenefitForCompanyBenefitValue.EmployeeBenefitForCompanyBenefitValueConverter))]
    public class EmployeeBenefitForCompanyBenefitValue {
        public EmployeeBenefitForCompanyBenefitValue(EmployeeBenefitForCompanyBenefitValueType type) {
            Type = type;
        }

        [SpeakeasyMetadata("form:explode=true")]
        public string? Str { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public Models.Components.Value2? Value2 { get; set; }

        public EmployeeBenefitForCompanyBenefitValueType Type { get; set; }


        public static EmployeeBenefitForCompanyBenefitValue CreateStr(string str) {
            EmployeeBenefitForCompanyBenefitValueType typ = EmployeeBenefitForCompanyBenefitValueType.Str;

            EmployeeBenefitForCompanyBenefitValue res = new EmployeeBenefitForCompanyBenefitValue(typ);
            res.Str = str;
            return res;
        }

        public static EmployeeBenefitForCompanyBenefitValue CreateValue2(Models.Components.Value2 value2) {
            EmployeeBenefitForCompanyBenefitValueType typ = EmployeeBenefitForCompanyBenefitValueType.Value2;

            EmployeeBenefitForCompanyBenefitValue res = new EmployeeBenefitForCompanyBenefitValue(typ);
            res.Value2 = value2;
            return res;
        }

        public static EmployeeBenefitForCompanyBenefitValue CreateNull() {
            EmployeeBenefitForCompanyBenefitValueType typ = EmployeeBenefitForCompanyBenefitValueType.Null;
            return new EmployeeBenefitForCompanyBenefitValue(typ);
        }

        public class EmployeeBenefitForCompanyBenefitValueConverter : JsonConverter
        {

            public override bool CanConvert(System.Type objectType) => objectType == typeof(EmployeeBenefitForCompanyBenefitValue);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            {
                var json = JRaw.Create(reader).ToString();
                if (json == "null")
                {
                    return null;
                }

                var fallbackCandidates = new List<(System.Type, object, string)>();

                try
                {
                    return new EmployeeBenefitForCompanyBenefitValue(EmployeeBenefitForCompanyBenefitValueType.Value2)
                    {
                        Value2 = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<Models.Components.Value2>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(Models.Components.Value2), new EmployeeBenefitForCompanyBenefitValue(EmployeeBenefitForCompanyBenefitValueType.Value2), "Value2"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                if (json[0] == '"' && json[^1] == '"'){
                    return new EmployeeBenefitForCompanyBenefitValue(EmployeeBenefitForCompanyBenefitValueType.Str)
                    {
                        Str = json[1..^1]
                    };
                }

                if (fallbackCandidates.Count > 0)
                {
                    fallbackCandidates.Sort((a, b) => ResponseBodyDeserializer.CompareFallbackCandidates(a.Item1, b.Item1, json));
                    foreach(var (deserializationType, returnObject, propertyName) in fallbackCandidates)
                    {
                        try
                        {
                            return ResponseBodyDeserializer.DeserializeUndiscriminatedUnionFallback(deserializationType, returnObject, propertyName, json);
                        }
                        catch (ResponseBodyDeserializer.DeserializationException)
                        {
                            // try next fallback option
                        }
                        catch (Exception)
                        {
                            throw;
                        }
                    }
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null) {
                    writer.WriteRawValue("null");
                    return;
                }
                EmployeeBenefitForCompanyBenefitValue res = (EmployeeBenefitForCompanyBenefitValue)value;
                if (EmployeeBenefitForCompanyBenefitValueType.FromString(res.Type).Equals(EmployeeBenefitForCompanyBenefitValueType.Null))
                {
                    writer.WriteRawValue("null");
                    return;
                }
                if (res.Str != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Str));
                    return;
                }
                if (res.Value2 != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Value2));
                    return;
                }

            }

        }

    }
}