//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace GustoEmbedded.Models.Components
{
    using GustoEmbedded.Utils;
    using Newtonsoft.Json;
    using System;
    
    /// <summary>
    /// |   |   |<br/>
    /// 
    /// <remarks>
    /// |---|---|<br/>
    /// |__Status__| __Description__ |<br/>
    /// | Pass | Signatory can sign all forms |<br/>
    /// | Fail | Signatory cannot sign forms |<br/>
    /// | Skipped | Signatory cannot sign Form 8655 until the form is manually uploaded as wet-signed |<br/>
    /// | null | Identity verification process has not been completed |
    /// </remarks>
    /// </summary>
    public enum IdentityVerificationStatus
    {
        [JsonProperty("Pass")]
        Pass,
        [JsonProperty("Fail")]
        Fail,
        [JsonProperty("Skipped")]
        Skipped,
    }

    public static class IdentityVerificationStatusExtension
    {
        public static string Value(this IdentityVerificationStatus value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static IdentityVerificationStatus ToEnum(this string value)
        {
            foreach(var field in typeof(IdentityVerificationStatus).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is IdentityVerificationStatus)
                    {
                        return (IdentityVerificationStatus)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum IdentityVerificationStatus");
        }
    }

}