//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace GustoEmbedded.Models.Components
{
    using GustoEmbedded.Models.Components;
    using GustoEmbedded.Utils;
    using Newtonsoft.Json;
    using System.Collections.Generic;
    
    /// <summary>
    /// Representation of a partners invoice data
    /// </summary>
    public class InvoiceData
    {

        /// <summary>
        /// The list of companies that are active within the invoice period
        /// </summary>
        [JsonProperty("active_companies")]
        public List<ActiveCompanies>? ActiveCompanies { get; set; }
    }
}