//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace GustoEmbedded.Models.Components
{
    using GustoEmbedded.Models.Components;
    using GustoEmbedded.Utils;
    using Newtonsoft.Json;
    using System.Collections.Generic;
    
    /// <summary>
    /// Example response
    /// </summary>
    public class PayrollReceipt
    {

        /// <summary>
        /// A unique identifier of the payroll receipt.
        /// </summary>
        [JsonProperty("payroll_uuid")]
        public string? PayrollUuid { get; set; }

        /// <summary>
        /// A unique identifier of the company for the payroll.
        /// </summary>
        [JsonProperty("company_uuid")]
        public string? CompanyUuid { get; set; }

        /// <summary>
        /// The name of the company by whom the payroll was paid
        /// </summary>
        [JsonProperty("name_of_sender")]
        public string? NameOfSender { get; set; }

        /// <summary>
        /// Always the fixed string &quot;Payroll Recipients&quot;
        /// </summary>
        [JsonProperty("name_of_recipient")]
        public string? NameOfRecipient { get; set; }

        /// <summary>
        /// Always the fixed string &quot;Payroll recipients include the employees listed below plus the tax agencies for the taxes listed below.&quot;
        /// </summary>
        [JsonProperty("recipient_notice")]
        public string? RecipientNotice { get; set; }

        /// <summary>
        /// The debit or funding date for the payroll
        /// </summary>
        [JsonProperty("debit_date")]
        public string? DebitDate { get; set; }

        /// <summary>
        /// Always the fixed string &quot;ZenPayroll, Inc., dba Gusto is a licensed money transmitter. For more about Gusto’s licenses and your state-specific rights to request information, submit complaints, dispute errors, or cancel transactions, visit our license page.&quot;
        /// </summary>
        [JsonProperty("license")]
        public string? License { get; set; }

        /// <summary>
        /// URL for the license information for the licensed payroll processor. Always the fixed string &quot;https://gusto.com/about/licenses&quot;
        /// </summary>
        [JsonProperty("license_uri")]
        public string? LicenseUri { get; set; }

        [JsonProperty("right_to_refund")]
        public string? RightToRefund { get; set; }

        [JsonProperty("liability_of_licensee")]
        public string? LiabilityOfLicensee { get; set; }

        /// <summary>
        /// The subtotals for the payroll.
        /// </summary>
        [JsonProperty("totals")]
        public Totals? Totals { get; set; }

        /// <summary>
        /// An array of totaled employer and employee taxes for the pay period.
        /// </summary>
        [JsonProperty("taxes")]
        public List<PayrollReceiptTaxes>? Taxes { get; set; }

        /// <summary>
        /// An array of employee compensations and withholdings for this payroll
        /// </summary>
        [JsonProperty("employee_compensations")]
        public List<Models.Components.EmployeeCompensations>? EmployeeCompensations { get; set; }

        /// <summary>
        /// The licensed payroll processor
        /// </summary>
        [JsonProperty("licensee")]
        public Licensee? Licensee { get; set; }
    }
}