//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace GustoEmbedded.Models.Components
{
    using GustoEmbedded.Models.Components;
    using GustoEmbedded.Utils;
    using Newtonsoft.Json;
    
    public class PayScheduleAssignmentEmployeeChange
    {

        /// <summary>
        /// The UUID of the employee.
        /// </summary>
        [JsonProperty("employee_uuid")]
        public string? EmployeeUuid { get; set; }

        /// <summary>
        /// The employee&apos;s first name.
        /// </summary>
        [JsonProperty("first_name")]
        public string? FirstName { get; set; }

        /// <summary>
        /// The employee&apos;s last name.
        /// </summary>
        [JsonProperty("last_name")]
        public string? LastName { get; set; }

        /// <summary>
        /// New pay schedule frequency and name.
        /// </summary>
        [JsonProperty("pay_frequency")]
        public string? PayFrequency { get; set; }

        /// <summary>
        /// Pay schedule assignment first pay period information.
        /// </summary>
        [JsonProperty("first_pay_period")]
        public PayScheduleAssignmentPayPeriod? FirstPayPeriod { get; set; }

        /// <summary>
        /// Pay schedule assignment transition pay period information.
        /// </summary>
        [JsonProperty("transition_pay_period")]
        public PayScheduleAssignmentTransitionPayPeriod? TransitionPayPeriod { get; set; }
    }
}