//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace GustoEmbedded.Models.Components
{
    using GustoEmbedded.Models.Components;
    using GustoEmbedded.Utils;
    using Newtonsoft.Json;
    
    public class RequiredAttributes
    {

        /// <summary>
        /// A required attribute when creating a garnishment for this state agency. The current values are listed as an enum; though unlikely, values could be added if state agency requirements change in the future.
        /// </summary>
        [JsonProperty("key")]
        public Key? Key { get; set; }

        /// <summary>
        /// A human readable name of the attribute, e.g. CSE Case Number
        /// </summary>
        [JsonProperty("label")]
        public string? Label { get; set; }
    }
}