//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace GustoEmbedded.Models.Components
{
    using GustoEmbedded.Utils;
    using Newtonsoft.Json;
    
    public class Resources
    {

        /// <summary>
        /// The type of entity being described, could be “Contractor”, “Employee”, “BankAccount”, “Payroll”, “ContractorPayment”, “RecoveryCase”, or “Signatory”
        /// </summary>
        [JsonProperty("entity_type")]
        public string EntityType { get; set; } = default!;

        /// <summary>
        /// Unique identifier of the entity
        /// </summary>
        [JsonProperty("entity_uuid")]
        public string EntityUuid { get; set; } = default!;

        /// <summary>
        /// Optional. The type of a resource that is related to the one described by entity_type and entity_uuid. For instance, if the entity_type is “BankAccount”, the reference_type could be the “Employee” or “Contractor” to whom the bank account belongs.
        /// </summary>
        [JsonProperty("reference_type")]
        public string? ReferenceType { get; set; }

        /// <summary>
        /// Optional. Unique identifier of the reference.
        /// </summary>
        [JsonProperty("reference_uuid")]
        public string? ReferenceUuid { get; set; }
    }
}