//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace GustoEmbedded.Models.Requests
{
    using GustoEmbedded.Models.Requests;
    using GustoEmbedded.Utils;
    using Newtonsoft.Json;
    using System.Collections.Generic;
    
    /// <summary>
    /// Submit wages, benefits, taxes for each employee
    /// </summary>
    public class ExternalPayrollItems
    {

        /// <summary>
        /// The UUID of the employee.
        /// </summary>
        [JsonProperty("employee_uuid")]
        public string? EmployeeUuid { get; set; }

        [JsonProperty("earnings")]
        public List<Models.Requests.Earnings>? Earnings { get; set; }

        [JsonProperty("benefits")]
        public List<Models.Requests.Benefits>? Benefits { get; set; }

        /// <summary>
        /// An array of taxes for the employee. Depends on your company selections, taxes include federal income tax, social security, medicare, and more.
        /// </summary>
        [JsonProperty("taxes")]
        public List<Models.Requests.Taxes>? Taxes { get; set; }
    }
}