//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace GustoEmbedded.Models.Requests
{
    using GustoEmbedded.Utils;
    using Newtonsoft.Json;
    
    public class GetCompaniesCompanyUuidPaidHolidaysRequestBody
    {

        /// <summary>
        /// If a year is passed, paid holidays for that year will be returned. Otherwise, paid holidays for the next three years will be returned.
        /// </summary>
        [JsonProperty("year")]
        public string? Year { get; set; }
    }
}