//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace GustoEmbedded.Models.Requests
{
    using GustoEmbedded.Models.Components;
    using GustoEmbedded.Models.Requests;
    using GustoEmbedded.Utils;
    
    public class GetV1CompaniesCompanyIdPaySchedulesPreviewRequest
    {

        /// <summary>
        /// The UUID of the company
        /// </summary>
        [SpeakeasyMetadata("pathParam:style=simple,explode=false,name=company_id")]
        public string CompanyId { get; set; } = default!;

        /// <summary>
        /// The frequency that employees on this pay schedule are paid with Gusto.
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=frequency")]
        public QueryParamFrequency Frequency { get; set; } = default!;

        /// <summary>
        /// The first date that employees on this pay schedule are paid with Gusto.
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=anchor_pay_date")]
        public string AnchorPayDate { get; set; } = default!;

        /// <summary>
        /// The last date of the first pay period. This can be the same date as the anchor pay date.
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=anchor_end_of_pay_period")]
        public string AnchorEndOfPayPeriod { get; set; } = default!;

        /// <summary>
        /// An integer between 1 and 31 indicating the first day of the month that employees are paid. This field is only relevant for pay schedules with the “Twice per month” and “Monthly” frequencies. It will be null for pay schedules with other frequencies.
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=day_1")]
        public long? Day1 { get; set; }

        /// <summary>
        /// An integer between 1 and 31 indicating the second day of the month that employees are paid. This field is the second pay date for pay schedules with the &quot;Twice per month&quot; frequency. For semi-monthly pay schedules, set this field to 31. For months shorter than 31 days, we will set the second pay date to the last day of the month. It will be null for pay schedules with other frequencies.
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=day_2")]
        public long? Day2 { get; set; }

        /// <summary>
        /// Determines the date-based API version associated with your API call. If none is provided, your application&apos;s <a href="https://docs.gusto.com/embedded-payroll/docs/api-versioning#minimum-api-version">minimum API version</a> is used.
        /// </summary>
        [SpeakeasyMetadata("header:style=simple,explode=false,name=X-Gusto-API-Version")]
        public VersionHeader? XGustoAPIVersion { get; set; } = GustoEmbedded.Models.Components.VersionHeader.TwoThousandAndTwentyFourMinus04Minus01;
    }
}