//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace GustoEmbedded.Models.Requests
{
    using GustoEmbedded.Models.Components;
    using GustoEmbedded.Utils;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using System;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;
    

    public class PostV1PlaidProcessorTokenResponseBodyType
    {
        private PostV1PlaidProcessorTokenResponseBodyType(string value) { Value = value; }

        public string Value { get; private set; }
        public static PostV1PlaidProcessorTokenResponseBodyType CompanyBankAccount { get { return new PostV1PlaidProcessorTokenResponseBodyType("Company-Bank-Account"); } }
        
        public static PostV1PlaidProcessorTokenResponseBodyType Null { get { return new PostV1PlaidProcessorTokenResponseBodyType("null"); } }

        public override string ToString() { return Value; }
        public static implicit operator String(PostV1PlaidProcessorTokenResponseBodyType v) { return v.Value; }
        public static PostV1PlaidProcessorTokenResponseBodyType FromString(string v) {
            switch(v) {
                case "Company-Bank-Account": return CompanyBankAccount;
                case "null": return Null;
                default: throw new ArgumentException("Invalid value for PostV1PlaidProcessorTokenResponseBodyType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((PostV1PlaidProcessorTokenResponseBodyType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }


    /// <summary>
    /// A JSON object containing bank information
    /// </summary>
    [JsonConverter(typeof(PostV1PlaidProcessorTokenResponseBody.PostV1PlaidProcessorTokenResponseBodyConverter))]
    public class PostV1PlaidProcessorTokenResponseBody {
        public PostV1PlaidProcessorTokenResponseBody(PostV1PlaidProcessorTokenResponseBodyType type) {
            Type = type;
        }

        [SpeakeasyMetadata("form:explode=true")]
        public CompanyBankAccount? CompanyBankAccount { get; set; }

        public PostV1PlaidProcessorTokenResponseBodyType Type { get; set; }


        public static PostV1PlaidProcessorTokenResponseBody CreateCompanyBankAccount(CompanyBankAccount companyBankAccount) {
            PostV1PlaidProcessorTokenResponseBodyType typ = PostV1PlaidProcessorTokenResponseBodyType.CompanyBankAccount;

            PostV1PlaidProcessorTokenResponseBody res = new PostV1PlaidProcessorTokenResponseBody(typ);
            res.CompanyBankAccount = companyBankAccount;
            return res;
        }

        public static PostV1PlaidProcessorTokenResponseBody CreateNull() {
            PostV1PlaidProcessorTokenResponseBodyType typ = PostV1PlaidProcessorTokenResponseBodyType.Null;
            return new PostV1PlaidProcessorTokenResponseBody(typ);
        }

        public class PostV1PlaidProcessorTokenResponseBodyConverter : JsonConverter
        {

            public override bool CanConvert(System.Type objectType) => objectType == typeof(PostV1PlaidProcessorTokenResponseBody);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            {
                var json = JRaw.Create(reader).ToString();
                if (json == "null")
                {
                    return null;
                }

                var fallbackCandidates = new List<(System.Type, object, string)>();

                try
                {
                    return new PostV1PlaidProcessorTokenResponseBody(PostV1PlaidProcessorTokenResponseBodyType.CompanyBankAccount)
                    {
                        CompanyBankAccount = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<CompanyBankAccount>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(CompanyBankAccount), new PostV1PlaidProcessorTokenResponseBody(PostV1PlaidProcessorTokenResponseBodyType.CompanyBankAccount), "CompanyBankAccount"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                if (fallbackCandidates.Count > 0)
                {
                    fallbackCandidates.Sort((a, b) => ResponseBodyDeserializer.CompareFallbackCandidates(a.Item1, b.Item1, json));
                    foreach(var (deserializationType, returnObject, propertyName) in fallbackCandidates)
                    {
                        try
                        {
                            return ResponseBodyDeserializer.DeserializeUndiscriminatedUnionFallback(deserializationType, returnObject, propertyName, json);
                        }
                        catch (ResponseBodyDeserializer.DeserializationException)
                        {
                            // try next fallback option
                        }
                        catch (Exception)
                        {
                            throw;
                        }
                    }
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null) {
                    writer.WriteRawValue("null");
                    return;
                }
                PostV1PlaidProcessorTokenResponseBody res = (PostV1PlaidProcessorTokenResponseBody)value;
                if (PostV1PlaidProcessorTokenResponseBodyType.FromString(res.Type).Equals(PostV1PlaidProcessorTokenResponseBodyType.Null))
                {
                    writer.WriteRawValue("null");
                    return;
                }
                if (res.CompanyBankAccount != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.CompanyBankAccount));
                    return;
                }

            }

        }

    }
}