//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace GustoEmbedded.Models.Requests
{
    using GustoEmbedded.Utils;
    using Newtonsoft.Json;
    using System;
    
    /// <summary>
    /// Payment method to filter by
    /// </summary>
    public enum PostCompaniesCompanyUuidReportsPaymentMethod
    {
        [JsonProperty("check")]
        Check,
        [JsonProperty("direct_deposit")]
        DirectDeposit,
    }

    public static class PostCompaniesCompanyUuidReportsPaymentMethodExtension
    {
        public static string Value(this PostCompaniesCompanyUuidReportsPaymentMethod value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static PostCompaniesCompanyUuidReportsPaymentMethod ToEnum(this string value)
        {
            foreach(var field in typeof(PostCompaniesCompanyUuidReportsPaymentMethod).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is PostCompaniesCompanyUuidReportsPaymentMethod)
                    {
                        return (PostCompaniesCompanyUuidReportsPaymentMethod)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum PostCompaniesCompanyUuidReportsPaymentMethod");
        }
    }

}