//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace GustoEmbedded.Models.Requests
{
    using GustoEmbedded.Utils;
    using Newtonsoft.Json;
    using System;
    
    /// <summary>
    /// The company contribution scheme.<br/>
    /// 
    /// <remarks>
    /// <br/>
    /// `amount`: The company contributes a fixed amount per payroll. If elective is true, the contribution is matching, dollar-for-dollar.<br/>
    /// <br/>
    /// `percentage`: The company contributes a percentage of the payroll amount per payroll period. If elective is true, the contribution is matching, dollar-for-dollar.<br/>
    /// <br/>
    /// `tiered`: The size of the company contribution corresponds to the size of the employee deduction relative to a tiered matching scheme.
    /// </remarks>
    /// </summary>
    public enum PostV1EmployeesEmployeeIdEmployeeBenefitsType
    {
        [JsonProperty("tiered")]
        Tiered,
        [JsonProperty("percentage")]
        Percentage,
        [JsonProperty("amount")]
        Amount,
    }

    public static class PostV1EmployeesEmployeeIdEmployeeBenefitsTypeExtension
    {
        public static string Value(this PostV1EmployeesEmployeeIdEmployeeBenefitsType value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static PostV1EmployeesEmployeeIdEmployeeBenefitsType ToEnum(this string value)
        {
            foreach(var field in typeof(PostV1EmployeesEmployeeIdEmployeeBenefitsType).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is PostV1EmployeesEmployeeIdEmployeeBenefitsType)
                    {
                        return (PostV1EmployeesEmployeeIdEmployeeBenefitsType)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum PostV1EmployeesEmployeeIdEmployeeBenefitsType");
        }
    }

}