//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace GustoEmbedded.Models.Requests
{
    using GustoEmbedded.Utils;
    using Newtonsoft.Json;
    using System;
    
    /// <summary>
    /// The contractor’s wage type.<br/>
    /// 
    /// <remarks>
    /// 
    /// </remarks>
    /// </summary>
    public enum PutV1ContractorsContractorUuidWageType
    {
        [JsonProperty("Fixed")]
        Fixed,
        [JsonProperty("Hourly")]
        Hourly,
    }

    public static class PutV1ContractorsContractorUuidWageTypeExtension
    {
        public static string Value(this PutV1ContractorsContractorUuidWageType value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static PutV1ContractorsContractorUuidWageType ToEnum(this string value)
        {
            foreach(var field in typeof(PutV1ContractorsContractorUuidWageType).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is PutV1ContractorsContractorUuidWageType)
                    {
                        return (PutV1ContractorsContractorUuidWageType)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum PutV1ContractorsContractorUuidWageType");
        }
    }

}