//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace GustoEmbedded.Models.Requests
{
    using GustoEmbedded.Models.Requests;
    using GustoEmbedded.Utils;
    using Newtonsoft.Json;
    
    public class PutV1EmployeesEmployeeIdRehireRequestBody
    {

        /// <summary>
        /// The current version of the object. See the <a href="https://docs.gusto.com/embedded-payroll/docs/idempotency">versioning guide</a> for information on how to use this field.
        /// </summary>
        [JsonProperty("version")]
        public string Version { get; set; } = default!;

        /// <summary>
        /// The day when the employee returns to work.
        /// </summary>
        [JsonProperty("effective_date")]
        public string EffectiveDate { get; set; } = default!;

        /// <summary>
        /// The boolean flag indicating whether Gusto will file a new hire report for the employee.
        /// </summary>
        [JsonProperty("file_new_hire_report")]
        public bool FileNewHireReport { get; set; } = default!;

        /// <summary>
        /// The uuid of the employee&apos;s work location.
        /// </summary>
        [JsonProperty("work_location_uuid")]
        public string WorkLocationUuid { get; set; } = default!;

        /// <summary>
        /// The employee&apos;s employment status. Supplying an invalid option will set the employment_status to *not_set*.
        /// </summary>
        [JsonProperty("employment_status")]
        public Models.Requests.EmploymentStatus? EmploymentStatus { get; set; }

        /// <summary>
        /// Whether the employee is a two percent shareholder of the company. This field only applies to companies with an S-Corp entity type.
        /// </summary>
        [JsonProperty("two_percent_shareholder")]
        public bool? TwoPercentShareholder { get; set; }
    }
}