//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace GustoEmbedded.Models.Requests
{
    using GustoEmbedded.Utils;
    using Newtonsoft.Json;
    using System.Collections.Generic;
    
    public class PutV1CompanyIndustryRequestBody
    {

        /// <summary>
        /// Industry title
        /// </summary>
        [JsonProperty("title")]
        public string? Title { get; set; }

        /// <summary>
        /// North American Industry Classification System (NAICS) is used to classify businesses with a six digit number based on the primary type of work the business performs
        /// </summary>
        [JsonProperty("naics_code")]
        public string NaicsCode { get; set; } = default!;

        /// <summary>
        /// A list of Standard Industrial Classification (SIC) codes, which are four digit number that categorize the industries that companies belong to based on their business activities. If sic_codes is not passed in, we will perform an internal lookup with naics_code.
        /// </summary>
        [JsonProperty("sic_codes")]
        public List<string>? SicCodes { get; set; }
    }
}