//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace GustoEmbedded.Models.Requests
{
    using GustoEmbedded.Utils;
    using Newtonsoft.Json;
    
    public class Splits
    {

        /// <summary>
        /// The bank account ID<br/>
        /// 
        /// <remarks>
        /// 
        /// </remarks>
        /// </summary>
        [JsonProperty("uuid")]
        public string? Uuid { get; set; }

        /// <summary>
        /// The bank account name
        /// </summary>
        [JsonProperty("name")]
        public string? Name { get; set; }

        /// <summary>
        /// The order of priority for each payment split, with priority 1 being the first bank account paid. Priority must be unique and sequential.
        /// </summary>
        [JsonProperty("priority")]
        public long? Priority { get; set; }

        /// <summary>
        /// The cents amount allocated for each payment split
        /// </summary>
        [JsonProperty("split_amount")]
        public long? SplitAmount { get; set; } = null;
    }
}