name: Publish
permissions:
  checks: write
  contents: write
  pull-requests: write
  statuses: write
  id-token: write
"on":
  push:
    branches:
      - main
    paths:
      - gusto_embedded/.speakeasy/gen.lock
  workflow_dispatch: {}
jobs:
  publish:
    uses: Gusto/sdk-generation-action/.github/workflows/sdk-publish.yaml@main
    with:
      target: gusto
      runs-on: "{\"group\": \"gusto-ubuntu-default\"}"
    secrets:
      github_access_token: ${{ secrets.GITHUB_TOKEN }}
      nuget_api_key: ${{ secrets.NUGET_API_KEY }}
      speakeasy_api_key: ${{ secrets.SPEAKEASY_API_KEY }}
