//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace GustoEmbedded.Models.Requests
{
    using GustoEmbedded.Utils;
    using Newtonsoft.Json;
    using System;
    
    /// <summary>
    /// Accrual method of the time off policy
    /// </summary>
    public enum AccrualMethod
    {
        [JsonProperty("unlimited")]
        Unlimited,
        [JsonProperty("per_pay_period")]
        PerPayPeriod,
        [JsonProperty("per_calendar_year")]
        PerCalendarYear,
        [JsonProperty("per_anniversary_year")]
        PerAnniversaryYear,
        [JsonProperty("per_hour_worked")]
        PerHourWorked,
        [JsonProperty("per_hour_worked_no_overtime")]
        PerHourWorkedNoOvertime,
        [JsonProperty("per_hour_paid")]
        PerHourPaid,
        [JsonProperty("per_hour_paid_no_overtime")]
        PerHourPaidNoOvertime,
    }

    public static class AccrualMethodExtension
    {
        public static string Value(this AccrualMethod value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static AccrualMethod ToEnum(this string value)
        {
            foreach(var field in typeof(AccrualMethod).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is AccrualMethod)
                    {
                        return (AccrualMethod)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum AccrualMethod");
        }
    }

}