//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace GustoEmbedded.Models.Requests
{
    using GustoEmbedded.Utils;
    using Newtonsoft.Json;
    using System;
    
    /// <summary>
    /// The type of document an employee holds, based on their authorization status.<br/>
    /// 
    /// <remarks>
    /// <br/>
    ///   * This is unused for authorization status `citizen` or `noncitizen`.<br/>
    ///   * If the authorization status is `permanent_resident`, this must be `uscis_alien_registration_number`.<br/>
    ///   * If the authorization status is `alien`, this is required and may be any of the valid values.<br/>
    /// 
    /// </remarks>
    /// </summary>
    public enum DocumentType
    {
        [JsonProperty("uscis_alien_registration_number")]
        UscisAlienRegistrationNumber,
        [JsonProperty("form_i94")]
        FormI94,
        [JsonProperty("foreign_passport")]
        ForeignPassport,
    }

    public static class DocumentTypeExtension
    {
        public static string Value(this DocumentType value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static DocumentType ToEnum(this string value)
        {
            foreach(var field in typeof(DocumentType).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is DocumentType)
                    {
                        return (DocumentType)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum DocumentType");
        }
    }

}