//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace GustoEmbedded.Models.Requests
{
    using GustoEmbedded.Models.Requests;
    using GustoEmbedded.Utils;
    using Newtonsoft.Json;
    
    public class PostV1CompaniesCompanyIdContractorPaymentGroupsPreviewContractorPayments
    {

        /// <summary>
        /// The contractor receiving the payment
        /// </summary>
        [JsonProperty("contractor_uuid")]
        public string? ContractorUuid { get; set; }

        [JsonProperty("payment_method")]
        public PostV1CompaniesCompanyIdContractorPaymentGroupsPreviewPaymentMethod? PaymentMethod { get; set; } = GustoEmbedded.Models.Requests.PostV1CompaniesCompanyIdContractorPaymentGroupsPreviewPaymentMethod.DirectDeposit;

        /// <summary>
        /// If the contractor is on a fixed wage, this is the fixed wage payment for the contractor, regardless of hours worked
        /// </summary>
        [JsonProperty("wage")]
        public double? Wage { get; set; }

        /// <summary>
        /// If the contractor is on an hourly wage, this is the number of hours that the contractor worked for the payment
        /// </summary>
        [JsonProperty("hours")]
        public double? Hours { get; set; }

        /// <summary>
        /// If the contractor is on an hourly wage, this is the bonus the contractor earned
        /// </summary>
        [JsonProperty("bonus")]
        public double? Bonus { get; set; }

        /// <summary>
        /// Reimbursed wages for the contractor
        /// </summary>
        [JsonProperty("reimbursement")]
        public double? Reimbursement { get; set; }
    }
}