//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace GustoEmbedded.Models.Requests
{
    using GustoEmbedded.Models.Requests;
    using GustoEmbedded.Utils;
    using Newtonsoft.Json;
    
    /// <summary>
    /// Create an individual or business contractor.
    /// </summary>
    public class PostV1CompaniesCompanyUuidContractorsRequestBody
    {

        /// <summary>
        /// The contractor type.
        /// </summary>
        [JsonProperty("type")]
        public PostV1CompaniesCompanyUuidContractorsType? Type { get; set; } = GustoEmbedded.Models.Requests.PostV1CompaniesCompanyUuidContractorsType.Individual;

        /// <summary>
        /// The contractor’s wage type.<br/>
        /// 
        /// <remarks>
        /// 
        /// </remarks>
        /// </summary>
        [JsonProperty("wage_type")]
        public Models.Requests.WageType WageType { get; set; } = default!;

        /// <summary>
        /// The day when the contractor will start working for the company.<br/>
        /// 
        /// <remarks>
        /// 
        /// </remarks>
        /// </summary>
        [JsonProperty("start_date")]
        public string StartDate { get; set; } = default!;

        /// <summary>
        /// The contractor’s hourly rate. This attribute is required if the wage_type is `Hourly`.
        /// </summary>
        [JsonProperty("hourly_rate")]
        public string? HourlyRate { get; set; }

        /// <summary>
        /// Whether the contractor or the payroll admin will complete onboarding in Gusto.<br/>
        /// 
        /// <remarks>
        /// Self-onboarding is recommended so that contractors receive Gusto accounts.<br/>
        /// If self_onboarding is true, then email is required.
        /// </remarks>
        /// </summary>
        [JsonProperty("self_onboarding")]
        public bool? SelfOnboarding { get; set; } = false;

        /// <summary>
        /// The contractor’s email address.
        /// </summary>
        [JsonProperty("email")]
        public string? Email { get; set; }

        /// <summary>
        /// The contractor’s first name.<br/>
        /// 
        /// <remarks>
        /// This attribute is required for `Individual` contractors and will be ignored for `Business` contractors.
        /// </remarks>
        /// </summary>
        [JsonProperty("first_name")]
        public string? FirstName { get; set; }

        /// <summary>
        /// The contractor’s last name.<br/>
        /// 
        /// <remarks>
        /// This attribute is required for `Individual` contractors and will be ignored for `Business` contractors.
        /// </remarks>
        /// </summary>
        [JsonProperty("last_name")]
        public string? LastName { get; set; }

        /// <summary>
        /// The contractor’s middle initial.<br/>
        /// 
        /// <remarks>
        /// This attribute is optional for `Individual` contractors and will be ignored for `Business` contractors.
        /// </remarks>
        /// </summary>
        [JsonProperty("middle_initial")]
        public string? MiddleInitial { get; set; }

        /// <summary>
        /// The boolean flag indicating whether Gusto will file a new hire report for the contractor.<br/>
        /// 
        /// <remarks>
        /// This attribute is optional for `Individual` contractors and will be ignored for `Business` contractors.
        /// </remarks>
        /// </summary>
        [JsonProperty("file_new_hire_report")]
        public bool? FileNewHireReport { get; set; } = false;

        /// <summary>
        /// State where the contractor will be conducting the majority of their work for the company.<br/>
        /// 
        /// <remarks>
        /// This value is used when generating the new hire report.<br/>
        /// This attribute is required for `Individual` contractors if `file_new_hire_report` is true and will be ignored for `Business` contractors.
        /// </remarks>
        /// </summary>
        [JsonProperty("work_state")]
        public string? WorkState { get; set; } = null;

        /// <summary>
        /// This attribute is optional for `Individual` contractors and will be ignored for `Business` contractors.<br/>
        /// 
        /// <remarks>
        /// Social security number is needed to file the annual 1099 tax form.
        /// </remarks>
        /// </summary>
        [JsonProperty("ssn")]
        public string? Ssn { get; set; }

        /// <summary>
        /// The name of the contractor business. This attribute is required for `Business` contractors and will be ignored for `Individual` contractors.
        /// </summary>
        [JsonProperty("business_name")]
        public string? BusinessName { get; set; }

        /// <summary>
        /// The employer identification number of the contractor business.<br/>
        /// 
        /// <remarks>
        /// This attribute is optional for `Business` contractors and will be ignored for `Individual` contractors.
        /// </remarks>
        /// </summary>
        [JsonProperty("ein")]
        public string? Ein { get; set; }

        /// <summary>
        /// The status of the contractor. If the contractor&apos;s start date is in the future, updating this field to true means we are setting the start date to today.
        /// </summary>
        [JsonProperty("is_active")]
        public bool? IsActive { get; set; }
    }
}