//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace GustoEmbedded.Models.Requests
{
    using GustoEmbedded.Models.Requests;
    using GustoEmbedded.Utils;
    using Newtonsoft.Json;
    
    public class PutV1CompaniesCompanyUuidSignatoriesSignatoryUuidRequestBody
    {

        /// <summary>
        /// The current version of the object. See the versioning guide for information on how to use this field.
        /// </summary>
        [JsonProperty("version")]
        public string? Version { get; set; }

        [JsonProperty("first_name")]
        public string? FirstName { get; set; }

        [JsonProperty("middle_initial")]
        public string? MiddleInitial { get; set; }

        [JsonProperty("last_name")]
        public string? LastName { get; set; }

        [JsonProperty("title")]
        public string? Title { get; set; }

        [JsonProperty("phone")]
        public string? Phone { get; set; }

        [JsonProperty("birthday")]
        public string? Birthday { get; set; }

        [JsonProperty("ssn")]
        public string? Ssn { get; set; }

        [JsonProperty("home_address")]
        public PutV1CompaniesCompanyUuidSignatoriesSignatoryUuidHomeAddress? HomeAddress { get; set; }
    }
}