//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace GustoEmbedded.Models.Requests
{
    using GustoEmbedded.Models.Components;
    using GustoEmbedded.Utils;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using System;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;
    

    public class PutV1CompanyPaymentConfigsRequestBodyType
    {
        private PutV1CompanyPaymentConfigsRequestBodyType(string value) { Value = value; }

        public string Value { get; private set; }
        public static PutV1CompanyPaymentConfigsRequestBodyType FastPaymentLimitRequiredBody { get { return new PutV1CompanyPaymentConfigsRequestBodyType("Fast-Payment-Limit-Required-Body"); } }
        
        public static PutV1CompanyPaymentConfigsRequestBodyType PaymentSpeedRequiredBody { get { return new PutV1CompanyPaymentConfigsRequestBodyType("Payment-Speed-Required-Body"); } }
        
        public static PutV1CompanyPaymentConfigsRequestBodyType Null { get { return new PutV1CompanyPaymentConfigsRequestBodyType("null"); } }

        public override string ToString() { return Value; }
        public static implicit operator String(PutV1CompanyPaymentConfigsRequestBodyType v) { return v.Value; }
        public static PutV1CompanyPaymentConfigsRequestBodyType FromString(string v) {
            switch(v) {
                case "Fast-Payment-Limit-Required-Body": return FastPaymentLimitRequiredBody;
                case "Payment-Speed-Required-Body": return PaymentSpeedRequiredBody;
                case "null": return Null;
                default: throw new ArgumentException("Invalid value for PutV1CompanyPaymentConfigsRequestBodyType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((PutV1CompanyPaymentConfigsRequestBodyType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }


    [JsonConverter(typeof(PutV1CompanyPaymentConfigsRequestBody.PutV1CompanyPaymentConfigsRequestBodyConverter))]
    public class PutV1CompanyPaymentConfigsRequestBody {
        public PutV1CompanyPaymentConfigsRequestBody(PutV1CompanyPaymentConfigsRequestBodyType type) {
            Type = type;
        }

        [SpeakeasyMetadata("form:explode=true")]
        public FastPaymentLimitRequiredBody? FastPaymentLimitRequiredBody { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public PaymentSpeedRequiredBody? PaymentSpeedRequiredBody { get; set; }

        public PutV1CompanyPaymentConfigsRequestBodyType Type { get; set; }


        public static PutV1CompanyPaymentConfigsRequestBody CreateFastPaymentLimitRequiredBody(FastPaymentLimitRequiredBody fastPaymentLimitRequiredBody) {
            PutV1CompanyPaymentConfigsRequestBodyType typ = PutV1CompanyPaymentConfigsRequestBodyType.FastPaymentLimitRequiredBody;

            PutV1CompanyPaymentConfigsRequestBody res = new PutV1CompanyPaymentConfigsRequestBody(typ);
            res.FastPaymentLimitRequiredBody = fastPaymentLimitRequiredBody;
            return res;
        }

        public static PutV1CompanyPaymentConfigsRequestBody CreatePaymentSpeedRequiredBody(PaymentSpeedRequiredBody paymentSpeedRequiredBody) {
            PutV1CompanyPaymentConfigsRequestBodyType typ = PutV1CompanyPaymentConfigsRequestBodyType.PaymentSpeedRequiredBody;

            PutV1CompanyPaymentConfigsRequestBody res = new PutV1CompanyPaymentConfigsRequestBody(typ);
            res.PaymentSpeedRequiredBody = paymentSpeedRequiredBody;
            return res;
        }

        public static PutV1CompanyPaymentConfigsRequestBody CreateNull() {
            PutV1CompanyPaymentConfigsRequestBodyType typ = PutV1CompanyPaymentConfigsRequestBodyType.Null;
            return new PutV1CompanyPaymentConfigsRequestBody(typ);
        }

        public class PutV1CompanyPaymentConfigsRequestBodyConverter : JsonConverter
        {

            public override bool CanConvert(System.Type objectType) => objectType == typeof(PutV1CompanyPaymentConfigsRequestBody);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            {
                var json = JRaw.Create(reader).ToString();
                if (json == "null")
                {
                    return null;
                }

                var fallbackCandidates = new List<(System.Type, object, string)>();

                try
                {
                    return new PutV1CompanyPaymentConfigsRequestBody(PutV1CompanyPaymentConfigsRequestBodyType.FastPaymentLimitRequiredBody)
                    {
                        FastPaymentLimitRequiredBody = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<FastPaymentLimitRequiredBody>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(FastPaymentLimitRequiredBody), new PutV1CompanyPaymentConfigsRequestBody(PutV1CompanyPaymentConfigsRequestBodyType.FastPaymentLimitRequiredBody), "FastPaymentLimitRequiredBody"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                try
                {
                    return new PutV1CompanyPaymentConfigsRequestBody(PutV1CompanyPaymentConfigsRequestBodyType.PaymentSpeedRequiredBody)
                    {
                        PaymentSpeedRequiredBody = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<PaymentSpeedRequiredBody>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(PaymentSpeedRequiredBody), new PutV1CompanyPaymentConfigsRequestBody(PutV1CompanyPaymentConfigsRequestBodyType.PaymentSpeedRequiredBody), "PaymentSpeedRequiredBody"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                if (fallbackCandidates.Count > 0)
                {
                    fallbackCandidates.Sort((a, b) => ResponseBodyDeserializer.CompareFallbackCandidates(a.Item1, b.Item1, json));
                    foreach(var (deserializationType, returnObject, propertyName) in fallbackCandidates)
                    {
                        try
                        {
                            return ResponseBodyDeserializer.DeserializeUndiscriminatedUnionFallback(deserializationType, returnObject, propertyName, json);
                        }
                        catch (ResponseBodyDeserializer.DeserializationException)
                        {
                            // try next fallback option
                        }
                        catch (Exception)
                        {
                            throw;
                        }
                    }
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null) {
                    writer.WriteRawValue("null");
                    return;
                }
                PutV1CompanyPaymentConfigsRequestBody res = (PutV1CompanyPaymentConfigsRequestBody)value;
                if (PutV1CompanyPaymentConfigsRequestBodyType.FromString(res.Type).Equals(PutV1CompanyPaymentConfigsRequestBodyType.Null))
                {
                    writer.WriteRawValue("null");
                    return;
                }
                if (res.FastPaymentLimitRequiredBody != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.FastPaymentLimitRequiredBody));
                    return;
                }
                if (res.PaymentSpeedRequiredBody != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.PaymentSpeedRequiredBody));
                    return;
                }

            }

        }

    }
}