//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace GustoEmbedded.Models.Requests
{
    using GustoEmbedded.Utils;
    using Newtonsoft.Json;
    
    public class PutV1EmployeesEmployeeIdI9AuthorizationEmployerSignRequestBody
    {

        /// <summary>
        /// The signature
        /// </summary>
        [JsonProperty("signature_text")]
        public string SignatureText { get; set; } = default!;

        /// <summary>
        /// The signer&apos;s job title
        /// </summary>
        [JsonProperty("signer_title")]
        public string SignerTitle { get; set; } = default!;

        /// <summary>
        /// The IP address of the signatory who signed the form. Both IPv4 AND IPv6 are supported. You must provide the IP address with either this parameter OR you can leave out this parameter and set the IP address in the request header using the `x-gusto-client-ip` header instead.
        /// </summary>
        [JsonProperty("signed_by_ip_address")]
        public string? SignedByIpAddress { get; set; }

        /// <summary>
        /// Whether you agree to sign electronically
        /// </summary>
        [JsonProperty("agree")]
        public bool Agree { get; set; } = default!;

        /// <summary>
        /// Any additional notes
        /// </summary>
        [JsonProperty("additional_info")]
        public string? AdditionalInfo { get; set; }

        /// <summary>
        /// Whether an alternative procedure authorized by DHS to examine documents was used
        /// </summary>
        [JsonProperty("alt_procedure")]
        public bool? AltProcedure { get; set; }
    }
}